"""intervals stage: apply patches, sync JSON, compute keep intervals."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import spacy

from nagare_clip.audio_silence.cuts_file import read_cuts
from nagare_clip.edit_lines import (
    expected_silences,
    gap_spans,
    parse_edit_lines,
    silence_line_min,
    silence_problems,
)
from nagare_clip.intervals.bunsetu import build_bunsetu_times, bunsetu_join_text
from nagare_clip.intervals.intervals import snap_overlay_starts
from nagare_clip.intervals.io import infer_source_file
from nagare_clip.intervals.keep import compute_keep_intervals
from nagare_clip.intervals.op_times import OpTimes
from nagare_clip.intervals.sync_json import (
    extract_cut_silences,
    extract_keep_ranges,
    extract_overlay_marks,
    extract_speed_ranges,
    sync_text_to_json,
)
from nagare_clip.timing import segment_times


def run_intervals(
    edits_txt: Path,
    json_path: Path,
    output: Path,
    cfg: dict,
    *,
    cuts_txt: Path | None = None,
    extra: OpTimes | None = None,
) -> None:
    """*extra* carries the ranges resolved from director ops that address a
    silence (``"n~"``).  Those have no words to wrap, so they can never arrive
    as text markers; they are unioned with the marker-derived ranges here so
    one code path follows.  ``None`` is exactly today's behaviour."""
    ivl = cfg["intervals"]
    cap = ivl["caption"]
    bun = ivl["bunsetu"]

    # --- Sync edit lines → JSON (applies {{old->new}} patches internally) ---
    edit_lines = edits_txt.read_text(encoding="utf-8").splitlines()
    logging.info("intervals: syncing edits from %s", edits_txt.name)

    with json_path.open("r", encoding="utf-8") as f:
        whisperx_data = json.load(f)

    # Silence lines are generated by guided_edit and identified by position;
    # one missing or out of place would move every marker on the lines after
    # it, so the file is refused, as a text change without a patch is.
    min_seconds = silence_line_min(cfg.get("director", {}))
    problems = silence_problems(
        parse_edit_lines(edit_lines), expected_silences(whisperx_data, min_seconds), min_seconds
    )
    if problems:
        line, message = problems[0]
        raise ValueError(f"{edits_txt.name} line {line}: {message}")
    # From the ORIGINAL timings: a <cut> that deletes a line must not move the
    # silence after it.
    silences = gap_spans(whisperx_data)

    whisperx_data = sync_text_to_json(whisperx_data, edit_lines)
    force_keep_ranges = extract_keep_ranges(edit_lines, whisperx_data, silences=silences)
    speed_ranges = extract_speed_ranges(edit_lines, whisperx_data, silences=silences)
    overlay_marks = extract_overlay_marks(edit_lines, whisperx_data, silences=silences)
    cut_silences = extract_cut_silences(edit_lines, silences)
    if extra is not None:
        force_keep_ranges = force_keep_ranges + extra.keeps
        speed_ranges = speed_ranges + extra.speeds
        overlay_marks = overlay_marks + extra.overlays
        logging.info(
            "Resolved from director silence refs: %d keep(s), %d speed(s), %d overlay(s)",
            len(extra.keeps),
            len(extra.speeds),
            len(extra.overlays),
        )
    if force_keep_ranges:
        logging.info("Force-keep ranges from <keep>: %d", len(force_keep_ranges))
    if speed_ranges:
        logging.info("Speed ranges from <speed>: %d", len(speed_ranges))
    if overlay_marks:
        logging.info("Overlay marks from <overlay/>: %d", len(overlay_marks))

    logging.info(
        "Loaded %d segment(s) from %s",
        len(whisperx_data.get("segments", [])),
        json_path.name,
    )

    nlp = spacy.load("ja_ginza")
    all_bunsetu_times = build_bunsetu_times(
        whisperx_data,
        nlp,
        char_eps=bun["char_eps"],
        silence_max_word_span=bun["silence_max_word_span"],
    )

    cut_ranges: list[tuple[float, float]] = list(cut_silences)
    if cut_silences:
        logging.info("Silences under <cut>: %d", len(cut_silences))
    if cuts_txt:
        audio_cuts = read_cuts(Path(cuts_txt))
        cut_ranges.extend(audio_cuts)
        logging.info(
            "Audio-silence cuts unioned: %d range(s) from %s",
            len(audio_cuts),
            Path(cuts_txt).name,
        )

    result = compute_keep_intervals(
        whisperx_data,
        all_bunsetu_times,
        ivl,
        cut_ranges=cut_ranges,
        force_keep_ranges=force_keep_ranges,
    )
    keep_intervals_dicts = result.keep_intervals
    captions = result.captions
    duration_sec = result.duration_sec

    if overlay_marks:
        # Runs after every keep-interval pass: the anchor is snapped against the
        # final intervals, so a caption whose line opened on cut footage moves to
        # the line's first surviving moment instead of being dropped in blender.
        moved = snap_overlay_starts(
            overlay_marks, segment_times(whisperx_data), keep_intervals_dicts
        )
        for (before, _, text), (after, _, _) in zip(overlay_marks, moved):
            if after != before:
                logging.info(
                    "Overlay anchor snapped %.3f -> %.3f (cut line opening): %r",
                    before,
                    after,
                    text[:40],
                )
        overlay_marks = moved

        # Blender's TEXT strip wraps only at whitespace; free-form overlay
        # text otherwise has none. Reuses the caption separator/nlp already
        # loaded above rather than adding a second config knob.
        overlay_marks = [
            (start, duration, bunsetu_join_text(text, nlp, cap["bunsetu_separator"]))
            for start, duration, text in overlay_marks
        ]

    output_data = {
        "source_file": infer_source_file(whisperx_data, json_path),
        "duration_sec": round(duration_sec, 3),
        "keep_intervals": keep_intervals_dicts,
        "captions": captions,
    }
    if speed_ranges:
        # Speed ranges are emitted as an independent top-level array (like
        # overlays); the blender stage splits keep intervals at these boundaries so a
        # speed range may cover an arbitrary sub-range of a keep interval.
        output_data["speed_ranges"] = [
            {"start": round(s, 3), "end": round(e, 3), "factor": f} for s, e, f in speed_ranges
        ]
    if overlay_marks:
        # An overlay is a point + a duration in *edited-timeline* seconds; the
        # blender stage measures it in output frames, so cuts and speed ranges
        # inside the window cannot shorten the reading time.
        output_data["overlays"] = [
            {"start": round(s, 3), "duration": round(d, 3), "text": t} for s, d, t in overlay_marks
        ]

    output.parent.mkdir(parents=True, exist_ok=True)
    logging.info("Writing output to %s", output)
    with output.open("w", encoding="utf-8") as f:
        json.dump(output_data, f, ensure_ascii=False, indent=2)
        f.write("\n")
