"""check_edits on a file with silence lines.

Silence lines are generated by guided_edit, never hand-added: deleting, moving
or duplicating one is an error like deleting transcript text, reported with
the physical line it concerns.  Only markers may be added or removed on or
around one; its seconds and description are ignored.
"""

from __future__ import annotations

from nagare_clip.edit_lines import gap_spans, insert_silence_lines
from nagare_clip.intervals.check_edits import check_edits, main

from .silence_equivalence_cases import TEXT_FILTER_LINES, WHISPERX

BODIES = {n: f"[silent {e - s:.1f}s]" for n, (s, e) in gap_spans(WHISPERX).items() if e - s >= 5.0}


def _file(**marks):
    # 1 あい, 2 S1, 3 うえ, 4 おか, 5 S3, 6 きく, 7 S4, 8 けこ, 9 さし
    lines = insert_silence_lines(TEXT_FILTER_LINES, BODIES)
    for key, text in marks.items():
        lines[int(key[1:]) - 1] = text
    return lines


def _check(lines, **kw):
    return [(p.line, p.message) for p in check_edits(lines, WHISPERX, **kw)]


def test_a_generated_file_with_markers_is_clean():
    lines = _file(
        l2='<keep><speed factor="8.0"><overlay text="x" duration="1.25"/>[silent 10.0s]',
        l4="おか</speed></keep>",
        l7="<cut>[silent 6.0s]</cut>",
    )
    assert _check(lines) == []


def test_a_legacy_file_is_still_clean():
    assert _check(TEXT_FILTER_LINES) == []


def test_a_deleted_silence_line_is_named_and_the_count_still_matches():
    lines = _file()
    del lines[4]
    ((line, message),) = _check(lines)
    assert line == 5
    assert "missing silence line after speech line 3" in message


def test_a_duplicated_silence_line_is_named():
    lines = _file()
    lines.insert(2, "[silent 10.0s]")
    ((line, message),) = _check(lines)
    assert line == 3
    assert "duplicate silence line after speech line 1" in message


def test_a_moved_silence_line_is_named_twice():
    lines = _file()
    lines[1], lines[2] = lines[2], lines[1]  # S1 moved below line 2
    problems = _check(lines)
    assert [line for line, _ in problems] == [2, 3]


def test_text_on_a_silence_line_is_named():
    problems = _check(_file(l2="[silent 10.0s]えー"))
    assert any(line == 2 and "may carry only markers" in msg for line, msg in problems)


def test_an_edited_description_is_fine():
    assert _check(_file(l2="[silent 3.0s: what I saw]")) == []


def test_tags_balance_across_silence_lines():
    assert _check(_file(l2="<keep>[silent 10.0s]", l3="うえ</keep>")) == []
    ((line, message),) = _check(_file(l5="<keep>[silent 8.0s]"))
    assert (line, message) == (5, "unclosed <keep> (opened here, never closed)")


def test_the_body_is_never_scanned_for_tags_or_patches():
    assert _check(_file(l2="[silent 10.0s: a <keep sign {{ \\] }}]")) == []


def test_a_changed_speech_line_is_named_by_its_physical_line():
    problems = _check(_file(l4="おかし"))
    assert [line for line, _ in problems] == [4]


def test_the_silence_set_follows_silence_line_min():
    ((line, message),) = _check(_file(), silence_line_min=7.0)
    assert line == 7
    assert "unexpected silence line after speech line 4" in message


def test_cli_takes_the_threshold(tmp_path, capsys):
    import json

    import pytest

    (tmp_path / "e.txt").write_text("\n".join(_file()) + "\n", encoding="utf-8")
    (tmp_path / "w.json").write_text(json.dumps(WHISPERX), encoding="utf-8")
    args = ["--edits-txt", str(tmp_path / "e.txt"), "--json", str(tmp_path / "w.json")]
    with pytest.raises(SystemExit) as ok:
        main(args)
    assert ok.value.code == 0
    with pytest.raises(SystemExit) as bad:
        main([*args, "--silence-line-min", "7"])
    assert bad.value.code == 1
    assert "unexpected silence line after speech line 4" in capsys.readouterr().out
